services:
  drf-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    networks:
      - internal

  # Banco de Dados PostgreSQL (opcional)
  # Recomendado usar um banco de dados externo para produção.

    depends_on:
       - postgres

  postgres:
     image: postgres:17-alpine
     container_name: postgres
     environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=${DB_NAME}
     env_file: .env
     volumes:
       - postgres-data:/var/lib/postgresql/data
     networks:
       - internal

networks:
  internal:

volumes:
  postgres-data: