services:
  drf-api:
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"