# Generated by Django 5.2 on 2025-08-31 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Exercício')),
                ('muscle_group', models.CharField(max_length=100, verbose_name='Grupo Muscular')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
        migrations.CreateModel(
            name='PersonalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_morning', models.FloatField()),
                ('weight_night', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peso Pessoal',
                'verbose_name_plural': 'Pesos Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('reps', models.IntegerField(verbose_name='Repetições')),
                ('set_number', models.IntegerField(verbose_name='Número da Série')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='main.exercise', verbose_name='Exercício')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.day', verbose_name='Sessão de Treino')),
            ],
            options={
                'verbose_name': 'Exercício do Treino',
                'verbose_name_plural': 'Exercícios do Treino',
            },
        ),
    ]
