name: Pipeline CI: Testes Django

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test-django:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    env:
      SECRET_KEY: "fake-key"
      DEBUG: "True"
      DB_USED: "sqlite"
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      CORS_ALLOW: "http://localhost:1234"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run makemigrations
        run: |
          python manage.py makemigrations

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test --verbosity=2
